name: package_name
version: 0.0.1
description: << Write your description here (not less than 60 characters). >>
homepage: https://zamstation.com
repository: https://github.com/zamstation/package_name

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  zam_core: ^0.5.0

dev_dependencies:
  zam_test: ^0.3.0
