name: zam_view_models
version: 0.1.0
description: A library of commonly used view models for all zamstation apps.
homepage: https://zamstation.com
repository: https://github.com/zamstation/zam_view_models

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  zam_core: ^0.7.0

dev_dependencies:
  lints: ^2.0.0
  zam_test: ^0.5.0
