name: zam_view_models
version: 0.0.1
description: A library of commonly used view models for all zamstation apps.
homepage: https://zamstation.com
repository: https://github.com/zamstation/zam_view_models

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  zam_core: ^0.6.0

dev_dependencies:
  lints: ^1.0.1
  zam_test: ^0.4.0
